# Generated by Django 2.2.6 on 2019-10-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191014_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSliderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SliderImagesOne', models.ImageField(blank=True, upload_to='sliders/')),
                ('SliderImagesTwo', models.ImageField(blank=True, upload_to='sliders/')),
                ('SliderImagesThree', models.ImageField(upload_to='sliders/')),
                ('SliderImagesFour', models.ImageField(upload_to='sliders/')),
                ('GetStartedHref', models.CharField(max_length=520)),
                ('SliderContentOne', models.CharField(max_length=520)),
                ('SliderContentTwo', models.CharField(max_length=520)),
                ('SliderContentThree', models.CharField(max_length=520)),
                ('SliderContentFour', models.CharField(max_length=520)),
                ('SliderContentFive', models.CharField(max_length=520)),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
