# Generated by Django 2.2.6 on 2019-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20191015_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerslidercontent',
            name='GetStartedHref',
            field=models.CharField(blank=True, max_length=520),
        ),
        migrations.AlterField(
            model_name='headerslidercontent',
            name='SliderContentFive',
            field=models.CharField(blank=True, max_length=520),
        ),
        migrations.AlterField(
            model_name='headerslidercontent',
            name='SliderContentFour',
            field=models.CharField(blank=True, max_length=520),
        ),
        migrations.AlterField(
            model_name='headerslidercontent',
            name='SliderContentOne',
            field=models.CharField(blank=True, max_length=520),
        ),
        migrations.AlterField(
            model_name='headerslidercontent',
            name='SliderContentThree',
            field=models.CharField(blank=True, max_length=520),
        ),
        migrations.AlterField(
            model_name='headerslidercontent',
            name='SliderContentTwo',
            field=models.CharField(blank=True, max_length=520),
        ),
        migrations.AlterField(
            model_name='headerslidercontent',
            name='SliderImagesFour',
            field=models.ImageField(blank=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='headerslidercontent',
            name='SliderImagesThree',
            field=models.ImageField(blank=True, upload_to='sliders/'),
        ),
    ]
