# Generated by Django 2.2.6 on 2019-12-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigIntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
